services:
  - type: web
    name: memegenerator
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false