services:
  - type: web
    name: memegenerator
    env: python
    buildCommand: |
      apt-get update && apt-get install -y imagemagick
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.0